#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
eww daemon &
ewwbar &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a sxiv state=floating
bspc rule -a Sxiv state=floating
